import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Logo({ mousePosition, ...props }) {
    const ref = useRef();
    const { nodes, materials } = useGLTF("/ilin.glb");
    const sensitivity = 0.1; 
    const [rotation, setRotation] = useState({ x: 0, y: 0 });

    useFrame(() => {
        if (ref.current && mousePosition) {
            const targetRotationY = mousePosition.x * Math.PI * sensitivity;
            const targetRotationX = mousePosition.y * Math.PI * sensitivity;

            const lerpFactor = 0.05; // Коэффициент интерполяции для плавности

            // Плавно обновляем вращение
            setRotation(prevRotation => ({
                x: prevRotation.x + (targetRotationX - prevRotation.x) * lerpFactor,
                y: prevRotation.y + (targetRotationY - prevRotation.y) * lerpFactor,
            }));

            ref.current.rotation.y = rotation.y;
            ref.current.rotation.x = rotation.x;
        }
    });
    return (
      <group ref={ref} {...props} dispose={null}>
        <group
          position={[-0.234, -0.123, 0.154]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={8.962}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750.geometry}
            material={materials["SVGMat.754"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_1.geometry}
            material={materials["SVGMat.753"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_2.geometry}
            material={materials["SVGMat.755"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_3.geometry}
            material={materials["SVGMat.756"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_4.geometry}
            material={materials["SVGMat.757"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_5.geometry}
            material={materials["SVGMat.758"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_6.geometry}
            material={materials["SVGMat.759"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_7.geometry}
            material={materials["SVGMat.760"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_8.geometry}
            material={materials["SVGMat.761"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_9.geometry}
            material={materials["SVGMat.762"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_10.geometry}
            material={materials["SVGMat.763"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_11.geometry}
            material={materials["SVGMat.764"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_12.geometry}
            material={materials["SVGMat.765"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_13.geometry}
            material={materials["SVGMat.766"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_14.geometry}
            material={materials["SVGMat.767"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_15.geometry}
            material={materials["SVGMat.768"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_16.geometry}
            material={materials["SVGMat.769"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_17.geometry}
            material={materials["SVGMat.770"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_18.geometry}
            material={materials["SVGMat.771"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_19.geometry}
            material={materials["SVGMat.772"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_20.geometry}
            material={materials["SVGMat.773"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_21.geometry}
            material={materials["SVGMat.774"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_22.geometry}
            material={materials["SVGMat.775"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_23.geometry}
            material={materials["SVGMat.776"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_24.geometry}
            material={materials["SVGMat.777"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_25.geometry}
            material={materials["SVGMat.778"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_26.geometry}
            material={materials["SVGMat.779"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_27.geometry}
            material={materials["SVGMat.780"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_28.geometry}
            material={materials["SVGMat.781"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_29.geometry}
            material={materials["SVGMat.782"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_30.geometry}
            material={materials["SVGMat.783"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_31.geometry}
            material={materials["SVGMat.784"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_32.geometry}
            material={materials["SVGMat.785"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_33.geometry}
            material={materials["SVGMat.786"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_34.geometry}
            material={materials["SVGMat.787"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_35.geometry}
            material={materials["SVGMat.788"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_36.geometry}
            material={materials["SVGMat.789"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_37.geometry}
            material={materials["SVGMat.790"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_38.geometry}
            material={materials["SVGMat.791"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_39.geometry}
            material={materials["SVGMat.792"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_40.geometry}
            material={materials["SVGMat.793"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_41.geometry}
            material={materials["SVGMat.794"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_42.geometry}
            material={materials["SVGMat.795"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_43.geometry}
            material={materials["SVGMat.796"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_44.geometry}
            material={materials["SVGMat.797"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_45.geometry}
            material={materials["SVGMat.798"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_46.geometry}
            material={materials["SVGMat.799"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_47.geometry}
            material={materials["SVGMat.800"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_48.geometry}
            material={materials["SVGMat.801"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_49.geometry}
            material={materials["SVGMat.802"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_50.geometry}
            material={materials["SVGMat.803"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_51.geometry}
            material={materials["SVGMat.804"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_52.geometry}
            material={materials["SVGMat.805"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_53.geometry}
            material={materials["SVGMat.806"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_54.geometry}
            material={materials["SVGMat.807"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_55.geometry}
            material={materials["SVGMat.808"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_56.geometry}
            material={materials["SVGMat.809"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_57.geometry}
            material={materials["SVGMat.810"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_58.geometry}
            material={materials["SVGMat.811"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_59.geometry}
            material={materials["SVGMat.812"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_60.geometry}
            material={materials["SVGMat.813"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_61.geometry}
            material={materials["SVGMat.814"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_62.geometry}
            material={materials["SVGMat.815"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_63.geometry}
            material={materials["SVGMat.816"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_64.geometry}
            material={materials["SVGMat.817"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_65.geometry}
            material={materials["SVGMat.818"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_66.geometry}
            material={materials["SVGMat.819"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_67.geometry}
            material={materials["SVGMat.820"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_68.geometry}
            material={materials["SVGMat.821"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_69.geometry}
            material={materials["SVGMat.822"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_70.geometry}
            material={materials["SVGMat.823"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_71.geometry}
            material={materials["SVGMat.824"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_72.geometry}
            material={materials["SVGMat.825"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_73.geometry}
            material={materials["SVGMat.826"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_74.geometry}
            material={materials["SVGMat.827"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_75.geometry}
            material={materials["SVGMat.828"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_76.geometry}
            material={materials["SVGMat.829"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_77.geometry}
            material={materials["SVGMat.830"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_78.geometry}
            material={materials["SVGMat.831"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_79.geometry}
            material={materials["SVGMat.832"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_80.geometry}
            material={materials["SVGMat.833"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_81.geometry}
            material={materials["SVGMat.834"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_82.geometry}
            material={materials["SVGMat.835"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_83.geometry}
            material={materials["SVGMat.836"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_84.geometry}
            material={materials["SVGMat.837"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_85.geometry}
            material={materials["SVGMat.838"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_86.geometry}
            material={materials["SVGMat.839"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_87.geometry}
            material={materials["SVGMat.840"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_88.geometry}
            material={materials["SVGMat.841"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_89.geometry}
            material={materials["SVGMat.842"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_90.geometry}
            material={materials["SVGMat.843"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_91.geometry}
            material={materials["SVGMat.844"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_92.geometry}
            material={materials["SVGMat.845"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_93.geometry}
            material={materials["SVGMat.846"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_94.geometry}
            material={materials["SVGMat.847"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_95.geometry}
            material={materials["SVGMat.848"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_96.geometry}
            material={materials["SVGMat.849"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_97.geometry}
            material={materials["SVGMat.850"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_98.geometry}
            material={materials["SVGMat.851"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_99.geometry}
            material={materials["SVGMat.852"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_100.geometry}
            material={materials["SVGMat.853"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_101.geometry}
            material={materials["SVGMat.854"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_102.geometry}
            material={materials["SVGMat.855"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_103.geometry}
            material={materials["SVGMat.856"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_104.geometry}
            material={materials["SVGMat.857"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_105.geometry}
            material={materials["SVGMat.858"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_106.geometry}
            material={materials["SVGMat.859"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_107.geometry}
            material={materials["SVGMat.860"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_108.geometry}
            material={materials["SVGMat.861"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_109.geometry}
            material={materials["SVGMat.862"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_110.geometry}
            material={materials["SVGMat.863"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_111.geometry}
            material={materials["SVGMat.864"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_112.geometry}
            material={materials["SVGMat.865"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_113.geometry}
            material={materials["SVGMat.866"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_114.geometry}
            material={materials["SVGMat.867"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_115.geometry}
            material={materials["SVGMat.868"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_116.geometry}
            material={materials["SVGMat.869"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_117.geometry}
            material={materials["SVGMat.870"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_118.geometry}
            material={materials["SVGMat.871"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_119.geometry}
            material={materials["SVGMat.872"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_120.geometry}
            material={materials["SVGMat.873"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_121.geometry}
            material={materials["SVGMat.874"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_122.geometry}
            material={materials["SVGMat.875"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_123.geometry}
            material={materials["SVGMat.876"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_124.geometry}
            material={materials["SVGMat.877"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_125.geometry}
            material={materials["SVGMat.878"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_126.geometry}
            material={materials["SVGMat.879"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_127.geometry}
            material={materials["SVGMat.880"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_128.geometry}
            material={materials["SVGMat.881"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_129.geometry}
            material={materials["SVGMat.882"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_130.geometry}
            material={materials["SVGMat.883"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_131.geometry}
            material={materials["SVGMat.884"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_132.geometry}
            material={materials["SVGMat.885"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_133.geometry}
            material={materials["SVGMat.886"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_134.geometry}
            material={materials["SVGMat.887"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_135.geometry}
            material={materials["SVGMat.888"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_136.geometry}
            material={materials["SVGMat.889"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_137.geometry}
            material={materials["SVGMat.890"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_138.geometry}
            material={materials["SVGMat.891"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_139.geometry}
            material={materials["SVGMat.892"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_140.geometry}
            material={materials["SVGMat.893"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_141.geometry}
            material={materials["SVGMat.894"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_142.geometry}
            material={materials["SVGMat.895"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_143.geometry}
            material={materials["SVGMat.896"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_144.geometry}
            material={materials["SVGMat.897"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_145.geometry}
            material={materials["SVGMat.898"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_146.geometry}
            material={materials["SVGMat.899"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_147.geometry}
            material={materials["SVGMat.900"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_148.geometry}
            material={materials["SVGMat.902"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_149.geometry}
            material={materials["SVGMat.903"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_150.geometry}
            material={materials["SVGMat.904"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_151.geometry}
            material={materials["SVGMat.905"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_152.geometry}
            material={materials["SVGMat.906"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_153.geometry}
            material={materials["SVGMat.907"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_154.geometry}
            material={materials["SVGMat.908"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_155.geometry}
            material={materials["SVGMat.909"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_156.geometry}
            material={materials["SVGMat.910"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_157.geometry}
            material={materials["SVGMat.911"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_158.geometry}
            material={materials["SVGMat.912"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_159.geometry}
            material={materials["SVGMat.913"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_160.geometry}
            material={materials["SVGMat.914"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_161.geometry}
            material={materials["SVGMat.915"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_162.geometry}
            material={materials["SVGMat.916"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_163.geometry}
            material={materials["SVGMat.917"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_164.geometry}
            material={materials["SVGMat.918"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_165.geometry}
            material={materials["SVGMat.919"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_166.geometry}
            material={materials["SVGMat.920"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_167.geometry}
            material={materials["SVGMat.921"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_168.geometry}
            material={materials["SVGMat.922"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_169.geometry}
            material={materials["SVGMat.923"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_170.geometry}
            material={materials["SVGMat.924"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_171.geometry}
            material={materials["SVGMat.925"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_172.geometry}
            material={materials["SVGMat.926"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_173.geometry}
            material={materials["SVGMat.927"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_174.geometry}
            material={materials["SVGMat.928"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_175.geometry}
            material={materials["SVGMat.929"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_176.geometry}
            material={materials["SVGMat.930"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_177.geometry}
            material={materials["SVGMat.931"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_178.geometry}
            material={materials["SVGMat.932"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_179.geometry}
            material={materials["SVGMat.933"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_180.geometry}
            material={materials["SVGMat.934"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_181.geometry}
            material={materials["SVGMat.935"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_182.geometry}
            material={materials["SVGMat.936"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_183.geometry}
            material={materials["SVGMat.937"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_184.geometry}
            material={materials["SVGMat.938"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_185.geometry}
            material={materials["SVGMat.939"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_186.geometry}
            material={materials["SVGMat.940"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_187.geometry}
            material={materials["SVGMat.941"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_188.geometry}
            material={materials["SVGMat.942"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_189.geometry}
            material={materials["SVGMat.943"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_190.geometry}
            material={materials["SVGMat.944"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_191.geometry}
            material={materials["SVGMat.945"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_192.geometry}
            material={materials["SVGMat.946"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_193.geometry}
            material={materials["SVGMat.947"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_194.geometry}
            material={materials["SVGMat.948"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_195.geometry}
            material={materials["SVGMat.949"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_196.geometry}
            material={materials["SVGMat.950"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_197.geometry}
            material={materials["SVGMat.951"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_198.geometry}
            material={materials["SVGMat.952"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_199.geometry}
            material={materials["SVGMat.953"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_200.geometry}
            material={materials["SVGMat.954"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_201.geometry}
            material={materials["SVGMat.955"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_202.geometry}
            material={materials["SVGMat.956"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_203.geometry}
            material={materials["SVGMat.957"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_204.geometry}
            material={materials["SVGMat.958"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_205.geometry}
            material={materials["SVGMat.959"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_206.geometry}
            material={materials["SVGMat.960"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_207.geometry}
            material={materials["SVGMat.961"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_208.geometry}
            material={materials["SVGMat.962"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_209.geometry}
            material={materials["SVGMat.963"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_210.geometry}
            material={materials["SVGMat.964"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_211.geometry}
            material={materials["SVGMat.965"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_212.geometry}
            material={materials["SVGMat.966"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_213.geometry}
            material={materials["SVGMat.967"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_214.geometry}
            material={materials["SVGMat.969"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_215.geometry}
            material={materials["SVGMat.971"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_216.geometry}
            material={materials["SVGMat.972"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_217.geometry}
            material={materials["SVGMat.973"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_218.geometry}
            material={materials["SVGMat.974"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_219.geometry}
            material={materials["SVGMat.975"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_220.geometry}
            material={materials["SVGMat.976"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_221.geometry}
            material={materials["SVGMat.977"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_222.geometry}
            material={materials["SVGMat.978"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_223.geometry}
            material={materials["SVGMat.979"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_224.geometry}
            material={materials["SVGMat.980"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_225.geometry}
            material={materials["SVGMat.981"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_226.geometry}
            material={materials["SVGMat.983"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_227.geometry}
            material={materials["SVGMat.984"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_228.geometry}
            material={materials["SVGMat.985"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_229.geometry}
            material={materials["SVGMat.986"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_230.geometry}
            material={materials["SVGMat.987"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_231.geometry}
            material={materials["SVGMat.988"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_232.geometry}
            material={materials["SVGMat.989"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_233.geometry}
            material={materials["SVGMat.990"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_234.geometry}
            material={materials["SVGMat.991"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_235.geometry}
            material={materials["SVGMat.992"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_236.geometry}
            material={materials["SVGMat.993"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_237.geometry}
            material={materials["SVGMat.994"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_238.geometry}
            material={materials["SVGMat.995"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_239.geometry}
            material={materials["SVGMat.996"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_240.geometry}
            material={materials["SVGMat.997"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_241.geometry}
            material={materials["SVGMat.998"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_242.geometry}
            material={materials["SVGMat.999"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_243.geometry}
            material={materials["SVGMat.1000"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_244.geometry}
            material={materials["SVGMat.1001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_245.geometry}
            material={materials["SVGMat.1002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_246.geometry}
            material={materials["SVGMat.1003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Curve750_247.geometry}
            material={materials["SVGMat.1004"]}
          />
        </group>
      </group>
    );
  }
  
  useGLTF.preload("/ilin.glb");